# Generated by Django 5.1.2 on 2025-04-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0002_initial'),
        ('event', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='event.event'),
        ),
        migrations.AddField(
            model_name='movement',
            name='destination_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='property.property'),
        ),
        migrations.AddField(
            model_name='movement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='event.event'),
        ),
        migrations.AddField(
            model_name='movement',
            name='origin_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='property.property'),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='event.event'),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='female_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions_female', to='animal.animal'),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='male_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions_male', to='animal.animal'),
        ),
        migrations.AddField(
            model_name='slaughter',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaughters', to='event.event'),
        ),
        migrations.AddField(
            model_name='specialoccurrences',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_occurrences', to='event.event'),
        ),
        migrations.AddField(
            model_name='vacine',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='event.event'),
        ),
        migrations.AddField(
            model_name='weighing',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighings', to='event.event'),
        ),
    ]
