# Arquivo de configuração para o Netlify
# Local: frontend/netlify.toml

# Esta regra de redirecionamento atua como um proxy.
[[redirects]]
  # Qualquer requisição que o frontend fizer para /api/...
  from = "/api/*"

  # Será redirecionada pelo servidor do Netlify para o seu backend.
  # Substitua o IP pelo da sua instância EC2.
  to = "http://3.15.29.140:8000/:splat"

  # O status 200 diz ao Netlify para atuar como um proxy,
  # "espelhando" a resposta do seu backend.
  status = 200