services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    env_file:
      - ./.env
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=123
    depends_on:
      - blockchain
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          
      - /app/node_modules        
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend

  blockchain:
    build:
      context: .
      dockerfile: blockchain/Dockerfile    
    env_file:
      - ./.env
    volumes:
      - hardhat_data:/data
    ports:
      - "8545:8545"

volumes:
  hardhat_data: {}