services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin # Troque por uma senha segura
    depends_on:
      - blockchain
      - db # Adicionado dependência do banco de dados

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  blockchain:
    build:
      context: .
      dockerfile: blockchain/Dockerfile
    env_file:
      - ./.env
    volumes:
      - hardhat_data:/data
    ports:
      - "8545:8545"

  # SERVIÇO DO BANCO DE DADOS ADICIONADO ABAIXO
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env # Garanta que seu .env tenha as variáveis POSTGRES_*

volumes:
  hardhat_data: {}
  postgres_data: {} # Adicionado volume do postgres