services:

  nginx:
    build: ./nginx
    volumes:
      - static_data:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /code/entrypoint.sh
    volumes:
      - static_data:/code/staticfiles
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin # Troque por uma senha segura
    depends_on:
      # MUDANÇA IMPORTANTE ABAIXO
      - blockchain
      - db

  blockchain:
    build:
      context: .
      dockerfile: blockchain/Dockerfile
    env_file:
      - ./.env
    volumes:
      - hardhat_data:/data
    ports:
      - "8545:8545"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  hardhat_data: {}
  postgres_data: {}
  static_data: {}