# Use uma imagem oficial do Python como base
FROM python:3.11-slim

# Defina variáveis de ambiente
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Defina o diretório de trabalho
WORKDIR /code

# Instale as dependências do sistema (sem netcat, não é necessário para o dev server)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Instale as dependências Python
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copie o código do projeto
COPY . /code/

# Exponha a porta 8000
EXPOSE 8000

# Copie o NOVO entrypoint de desenvolvimento e torne-o executável
COPY ./entrypoint-dev.sh /code/entrypoint-dev.sh
RUN chmod +x /code/entrypoint-dev.sh

# Defina o entrypoint de desenvolvimento
ENTRYPOINT ["/code/entrypoint-dev.sh"]