# Generated by Django 5.1.2 on 2025-05-26 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_historicalanimal_historicalanimalgroup_and_more'),
        ('blockchain', '0004_historicalblockchain_historicalblockchainstatus'),
        ('event', '0003_historicalevent_historicaleventtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_entries', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_entries', to='event.event'),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_entries_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_entries_by_status', to='blockchain.blockchainstatus'),
        ),
    ]
