# Generated by Django 5.1.2 on 2025-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_blockchain_options_alter_blockchain_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='cost_currency_symbol',
            field=models.CharField(blank=True, default='WEI', help_text='Símbolo da moeda/unidade do custo (ex: WEI, GWEI)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='transaction_cost',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Custo da transação em Wei (gasUsed * effectiveGasPrice)', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalblockchain',
            name='cost_currency_symbol',
            field=models.CharField(blank=True, default='WEI', help_text='Símbolo da moeda/unidade do custo (ex: WEI, GWEI)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalblockchain',
            name='transaction_cost',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Custo da transação em Wei (gasUsed * effectiveGasPrice)', max_digits=30, null=True),
        ),
    ]
