# Generated by Django 5.1.2 on 2024-12-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='observartions',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
