# Generated by Django 5.1.2 on 2025-05-30 16:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0006_alter_animal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOwnershipTransferRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pendente de Aprovação'), ('APPROVED', 'Aprovada pelo Destinatário'), ('REJECTED', 'Rejeitada pelo Destinatário'), ('PROCESSING', 'Processando Transferência On-chain'), ('COMPLETED', 'Concluída'), ('FAILED_BLOCKCHAIN', 'Falha na Blockchain'), ('CANCELLED_BY_INITIATOR', 'Cancelada pelo Solicitante')], default='PENDING_APPROVAL', max_length=30, verbose_name='Status da Solicitação')),
                ('request_date', models.DateTimeField(blank=True, editable=False, verbose_name='Data da Solicitação')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Ação do Destinatário')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Efetiva')),
                ('initiator_notes', models.TextField(blank=True, null=True, verbose_name='Observações do Solicitante')),
                ('recipient_notes', models.TextField(blank=True, null=True, verbose_name='Observações do Destinatário (ao aceitar/rejeitar)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Proprietário Atual)')),
                ('requested_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário Solicitado')),
            ],
            options={
                'verbose_name': 'historical Solicitação de Transferência de Titularidade',
                'verbose_name_plural': 'historical Solicitações de Transferência de Titularidade',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OwnershipTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pendente de Aprovação'), ('APPROVED', 'Aprovada pelo Destinatário'), ('REJECTED', 'Rejeitada pelo Destinatário'), ('PROCESSING', 'Processando Transferência On-chain'), ('COMPLETED', 'Concluída'), ('FAILED_BLOCKCHAIN', 'Falha na Blockchain'), ('CANCELLED_BY_INITIATOR', 'Cancelada pelo Solicitante')], default='PENDING_APPROVAL', max_length=30, verbose_name='Status da Solicitação')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Ação do Destinatário')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Efetiva')),
                ('initiator_notes', models.TextField(blank=True, null=True, verbose_name='Observações do Solicitante')),
                ('recipient_notes', models.TextField(blank=True, null=True, verbose_name='Observações do Destinatário (ao aceitar/rejeitar)')),
                ('animals', models.ManyToManyField(related_name='transfer_requests_involved_in', to='animal.animal', verbose_name='Animais na Solicitação')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Proprietário Atual)')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário Solicitado')),
            ],
            options={
                'verbose_name': 'Solicitação de Transferência de Titularidade',
                'verbose_name_plural': 'Solicitações de Transferência de Titularidade',
                'ordering': ['-request_date'],
            },
        ),
    ]
